### ISSUE TITLE
Newest ultraviolet from crates.io fails to build

### ISSUE THREAD

**Issue by anula** [termhn/ultraviolet#35]
To replicate create a new cargo project, eg. with `cargo init test_ultraviolet`.
Then add the following to `Cargo.toml` (0.4.5 is the newest version at the time of writing this):
```
[dependencies]
ultraviolet = "0.4.5"
```
and try building the project with `cargo build`.

This results in the following error:
```
    Updating crates.io index
   Compiling wide v0.4.4
   Compiling bytemuck v1.2.0
   Compiling ultraviolet v0.4.5
error[E0599]: no method named `sin_cos` found for struct `wide::m_f32x4::f32x4` in the current scope
   --> /home/anula/.cargo/registry/src/github.com-1ecc6299db9ec823/ultraviolet-0.4.5/src/mat.rs:234:36
    |
234 |                 let (s, c) = angle.sin_cos();
    |                                    ^^^^^^^ method not found in `wide::m_f32x4::f32x4`
...
569 | mat3s!(Mat3 => Rotor3, Bivec3, Mat4, Vec4, Vec2, Vec3, f32, Wat3 => WRotor3, WBivec3, Wat4, Wec4, Wec2, Wec3, f32x4);
    | --------------------------------------------------------------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sin_cos` found for struct `wide::m_f32x4::f32x4` in the current scope
   --> /home/anula/.cargo/registry/src/github.com-1ecc6299db9ec823/ultraviolet-0.4.5/src/rotor.rs:110:45
    |
110 |                 let (sin, cos) = half_angle.sin_cos();
    |                                             ^^^^^^^ method not found in `wide::m_f32x4::f32x4`
...
319 | rotor2s!(Rotor2 => (Mat2, Vec2, Bivec2, f32), WRotor2 => (Wat2, Wec2, WBivec2, f32x4));
    | --------------------------------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sin_cos` found for struct `wide::m_f32x4::f32x4` in the current scope
   --> /home/anula/.cargo/registry/src/github.com-1ecc6299db9ec823/ultraviolet-0.4.5/src/rotor.rs:121:45
    |
121 |                 let (sin, cos) = half_angle.sin_cos();
    |                                             ^^^^^^^ method not found in `wide::m_f32x4::f32x4`
...
319 | rotor2s!(Rotor2 => (Mat2, Vec2, Bivec2, f32), WRotor2 => (Wat2, Wec2, WBivec2, f32x4));
    | --------------------------------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no method named `sin_cos` found for struct `wide::m_f32x4::f32x4` in the current scope
   --> /home/anula/.cargo/registry/src/github.com-1ecc6299db9ec823/ultraviolet-0.4.5/src/rotor.rs:370:45
    |
370 |                 let (sin, cos) = half_angle.sin_cos();
    |                                             ^^^^^^^ method not found in `wide::m_f32x4::f32x4`
...
677 | rotor3s!(Rotor3 => (Mat3, Vec3, Bivec3, f32), WRotor3 => (Wat3, Wec3, WBivec3, f32x4));
    | --------------------------------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ultraviolet`.

To learn more, run the command again with --verbose.
```

I believe the cause is the newest version of "wide" crate. ultraviolet seems to build with up to 0.4.3 wide version, but simply specifies "wide ^0.4" as dependency.

As a workaround, I can force wide to the older version with: `cargo update -p wide --precise 0.4.3` and the build succeeds.

**Comment by termhn** [comment]
Thanks for the report, I'm passing it along to the `wide` author as a patch version should not be breaking.

**Comment by steelx** [comment]
i was also facing the issue while trying to run `rltk: 0.8.0` 

Fix mentioned by @anula  `cargo update -p wide --precise 0.4.3` worked for me

**Comment by Lokathor** [comment]
Hi, `wide` author here.

Some unknown number of patches before the latest one have a math bug so `sin_cos` gives _very_ wrong answers for parts of the circle. https://github.com/Lokathor/wide/issues/26

I probably need to yank more old versions, because `0.4.3` will build but it will be very wrong.

The latest version still has the `sin_cos` method, but you need to enable the `extern_crate_std` library feature for it to be present. Until I have the time to go through the function again and find the math bug we'll have to use the standard library sin_cos like this.

**Comment by termhn** [comment]
Okay, I published `ultraviolet` 0.4.6, which should now work properly with the latest wide version and std feature enabled. I also yanked all previous 0.4.x versions of `ultraviolet`, which are now all probably broken for the same reason as 0.4.5 was.

Hopefully this should be fixed, if not feel free to reopen.
